data:
  type: imagelist
  train_dir: data/CACD
  test_dir: data/CACD
  train_src: sourcefiles/CACD_train.txt
  test_src: sourcefiles/CACD_val.txt
  img_size: 512
generator:
  name: resnet
  kwargs:
    nfilter: 16
    nfilter_max: 512
    embed_size: 256
discriminator:
  name: resnet
  kwargs:
    nfilter: 16
    nfilter_max: 512
    embed_size: 256
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: output/CACD
  batch_size: 24
test:
  batch_size: 4
  sample_size: 6
  sample_nrow: 3
interpolations:
  nzs: 10
  nsubsteps: 75
